name: Lawffice
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish the package

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust SDK version as needed

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2 # Check for the latest version
  firebase_core: ^2.15.0 # Check for the latest version
  firebase_messaging: ^14.6.4 # Corrected line, check for latest version
  http: ^0.13.0 # Check for the latest version
  path_provider: ^2.0.0 # Check for the latest version
  permission_handler: ^10.0.0 # Check for the latest version
  url_launcher: ^6.1.11 # Check for the latest version
  cupertino_icons: ^1.0.2 # Optional, for iOS icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
