name: Lawffice
version: 1.0.0+1
description: A Flutter WebView app with Firebase notifications and file handling

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.6.1
  flutter_webview_plugin: ^0.4.0
  firebase_messaging: ^14.6.5
  http: ^0.13.4
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  flutter_downloader: ^1.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
