name: Lawffice
description: A WebView app with Firebase Notifications

version: 1.0.0+1

environment:
  sdk: "^3.6.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.0
  firebase_messaging: ^14.7.0
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
