name: Flutter iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'  # Update to your Flutter version
          channel: 'stable'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install

      - name: Accept Xcode license
        run: sudo xcodebuild -license accept

      - name: Build iOS (unsigned)
        run: flutter build ios --release --no-codesign

      - name: Archive build
        run: |
          cd build/ios/iphoneos
          zip -r Runner.app.zip Runner.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app.zip
